In [44]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense,Activation
from keras.optimizers import SGD
x_train=np.array([[0,0],[0,1],[1,0],[1,1]])
y_train=np.array([[0],[1],[1],[0]])
model=Sequential()
num_neurons=10
model.add(Dense(num_neurons,input_dim=2))
model.add(Activation('tanh'))
model.add(Dense(1))
model.add(Activation('sigmoid'))
model.summary()


Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 10)                30        
_________________________________________________________________
activation_12 (Activation)   (None, 10)                0         
_________________________________________________________________
dense_13 (Dense)             (None, 1)                 11        
_________________________________________________________________
activation_13 (Activation)   (None, 1)                 0         
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


In [45]:
sgd=SGD(learning_rate=0.1)
model.compile(loss='binary_crossentropy',optimizer=sgd,metrics=['accuracy'])


In [46]:
model.predict(x_train)

array([[0.5       ],
       [0.45545596],
       [0.4080544 ],
       [0.36549783]], dtype=float32)

In [53]:
model.fit(x_train,y_train,epochs=300)

9/300
1/1 [==============================] - 0s 2ms/step - loss: 0.3769 - accuracy: 1.0000
Epoch 100/300
1/1 [==============================] - 0s 3ms/step - loss: 0.3756 - accuracy: 1.0000
Epoch 101/300
1/1 [==============================] - 0s 1ms/step - loss: 0.3743 - accuracy: 1.0000
Epoch 102/300
1/1 [==============================] - 0s 988us/step - loss: 0.3730 - accuracy: 1.0000
Epoch 103/300
1/1 [==============================] - 0s 1ms/step - loss: 0.3717 - accuracy: 1.0000
Epoch 104/300
1/1 [==============================] - 0s 1ms/step - loss: 0.3703 - accuracy: 1.0000
Epoch 105/300
1/1 [==============================] - 0s 1ms/step - loss: 0.3690 - accuracy: 1.0000
Epoch 106/300
1/1 [==============================] - 0s 1ms/step - loss: 0.3677 - accuracy: 1.0000
Epoch 107/300
1/1 [==============================] - 0s 1ms/step - loss: 0.3664 - accuracy: 1.0000
Epoch 108/300
1/1 [==============================] - 0s 2ms/step - loss: 0.3651 - accuracy: 1.0000
Epoch 109/300
1/

In [54]:
model.predict(x_train)

array([[0.08585235],
       [0.8468445 ],
       [0.8420676 ],
       [0.20259678]], dtype=float32)

In [55]:
model.predict_classes(x_train)

array([[0],
       [1],
       [1],
       [0]], dtype=int32)

In [58]:
import h5py
model_stucture=model.to_json()
with open('basic_model.json','w') as json_file:
    json_file.write(model_stucture)
model.save_weights('basic_weights.h5')